### ISSUE TITLE
Wikithis URL format update (1.4.4)

### ISSUE THREAD

**Issue by BasicallyIAmFox** [Flashkirby/CampingMod#13]
In case you don't know, the main mod call on Wikithis has changed. Will be enforced to the new format in 1.4.4. example:
`wiki.Call("AddModURL", calamity, "calamitymod.wiki.gg");` -> `wiki.Call("AddModURL", calamity, "https://calamitymod.wiki.gg/wiki/{}");`

**Comment by Flashkirby** [comment]
Thanks, I'll keep this in mind

**Comment by Flashkirby** [comment]
2ea834da
